# Generated by Django 4.0.4 on 2023-08-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_categoria_contenido_remove_categoria_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categorias',
            new_name='badge',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
