name: Django Deployment

on:
  push:
    branches:
      - feat/workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurando Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Instalando Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      - name: Desplegando a Produción
        # env:
        #   SECRET_KEY: ${{ secrets.SECRET_KEY }}
        #   DATABASE_URL: ${{ secrets.DATABASE_URL }}

        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
          python manage.py runserver
